junction .\Ashtech GG24
fsutil hardlink create .\Dcf\All ..\Main\All
fsutil hardlink create .\Dcf\Args.h .\Args.h
fsutil hardlink create .\Dcf\Macro.cfg .\Macro.cfg
fsutil hardlink create .\Dcf\Main.h .\Main.h
fsutil hardlink create .\G12\Args.h .\Args.h
fsutil hardlink create .\G12\Macro.cfg .\Macro.cfg
fsutil hardlink create .\G12\Main.h .\Main.h
fsutil hardlink create .\GG24\All ..\Main\All
fsutil hardlink create .\GG24\Args.h .\Args.h
fsutil hardlink create .\GG24\Macro.cfg .\Macro.cfg
fsutil hardlink create .\GG24\Main.h .\Main.h
fsutil hardlink create .\Gril\Args.h .\Args.h
fsutil hardlink create .\Gril\Macro.cfg .\Macro.cfg
fsutil hardlink create .\Gril\Main.h .\Main.h
fsutil hardlink create .\Main.h .\Main\Main.h
fsutil hardlink create .\MicroZ\All ..\Main\All
fsutil hardlink create .\MicroZ\Args.h .\Args.h
fsutil hardlink create .\MicroZ\Macro.cfg .\Macro.cfg
fsutil hardlink create .\MicroZ\Main.h .\Main.h
fsutil hardlink create .\Moto\All ..\Main\All
fsutil hardlink create .\Moto\Args.h .\Args.h
fsutil hardlink create .\Moto\Macro.cfg .\Macro.cfg
fsutil hardlink create .\Moto\Main.h .\Main.h
fsutil hardlink create .\Tsip\All ..\Main\All
fsutil hardlink create .\Tsip\Args.h .\Args.h
fsutil hardlink create .\Tsip\Macro.cfg .\Macro.cfg
fsutil hardlink create .\Tsip\Main.h .\Main.h
fsutil hardlink create .\Topcon\All ..\Main\All
fsutil hardlink create .\Topcon\Args.h .\Args.h
fsutil hardlink create .\Topcon\Macro.cfg .\Macro.cfg
fsutil hardlink create .\Topcon\Main.h .\Main.h
