fsutil hardlink create Defect.cfg ..\English\Defect.cfg
fsutil hardlink create Delay.cfg ..\English\Delay.cfg
fsutil hardlink create Dismount.cfg ..\English\Dismount.cfg
fsutil hardlink create Down.cfg ..\English\Down.cfg
fsutil hardlink create Goic.cfg ..\English\Goic.cfg
fsutil hardlink create Kp2.cfg ..\English\Kp2.cfg
fsutil hardlink create Kp.cfg ..\English\Kp.cfg
fsutil hardlink create Matl.cfg ..\English\Matl.cfg
fsutil hardlink create Nearby.cfg ..\English\Nearby.cfg
fsutil hardlink create Ok.cfg ..\English\Ok.cfg
fsutil hardlink create Options.cfg ..\English\Options.cfg
fsutil hardlink create Project.cfg ..\English\Project.cfg
fsutil hardlink create Reset.cfg ..\English\Reset.cfg
fsutil hardlink create Standby.cfg ..\English\Standby.cfg
fsutil hardlink create Status.cfg ..\English\Status.cfg
fsutil hardlink create w0.bGauges.cfg ..\English\w0.bGauges.cfg
fsutil hardlink create w0.cfg ..\English\w0.cfg
fsutil hardlink create w0.ht.cfg ..\English\w0.ht.cfg
fsutil hardlink create w0.Icon.cfg ..\English\w0.Icon.cfg
fsutil hardlink create w0.mb.cfg ..\English\w0.mb.cfg
fsutil hardlink create w0.Sl1.cfg ..\English\w0.Sl1.cfg
fsutil hardlink create w0.Sl2.cfg ..\English\w0.Sl2.cfg
fsutil hardlink create w0.Text.cfg ..\English\w0.Text.cfg
fsutil hardlink create w0.v1.cfg ..\English\w0.v1.cfg
fsutil hardlink create w0.v2.cfg ..\English\w0.v2.cfg
fsutil hardlink create w0.v3.cfg ..\English\w0.v3.cfg
fsutil hardlink create wGpsstat.cfg ..\..\common\wGpsstat.cfg
fsutil hardlink create WinMgr.cfg ..\English\WinMgr.cfg
fsutil hardlink create wProject.cfg ..\..\common\wProject.cfg
