fsutil hardlink create Client_Macro.cfg ..\English\Client_Macro.cfg
fsutil hardlink create KpMinus.cfg ..\English\KpMinus.cfg
fsutil hardlink create Spray2.cfg ..\English\Spray2.cfg
fsutil hardlink create w0.cfg ..\English\w0.cfg
fsutil hardlink create w0.Icon.cfg ..\English\w0.Icon.cfg
fsutil hardlink create w0.Text.cfg ..\English\w0.Text.cfg
fsutil hardlink create w0.v1.cfg ..\English\w0.v1.cfg
fsutil hardlink create w0.v2.cfg ..\English\w0.v2.cfg
fsutil hardlink create WinMgr.cfg ..\English\WinMgr.cfg
