fsutil hardlink create Blocks.cfg ..\English\Blocks.cfg
fsutil hardlink create Delay.cfg ..\English\Delay.cfg
fsutil hardlink create DelayL_.cfg ..\English\DelayL_.cfg
fsutil hardlink create Down.cfg ..\English\Down.cfg
fsutil hardlink create DownL_.cfg ..\English\DownL_.cfg
fsutil hardlink create Dozers.cfg ..\English\Dozers.cfg
fsutil hardlink create Drills.cfg ..\English\Drills.cfg
fsutil hardlink create Graders.cfg ..\English\Graders.cfg
fsutil hardlink create Ready.cfg ..\English\Ready.cfg
fsutil hardlink create ReadyL_.cfg ..\English\ReadyL_.cfg
fsutil hardlink create Shovels2.cfg ..\English\Shovels2.cfg
fsutil hardlink create Standby.cfg ..\English\Standby.cfg
fsutil hardlink create StandbyL_.cfg ..\English\StandbyL_.cfg
fsutil hardlink create Trucks3.cfg ..\English\Trucks3.cfg
fsutil hardlink create Trucks4.cfg ..\English\Trucks4.cfg
fsutil hardlink create w0.cfg ..\English\w0.cfg
fsutil hardlink create w0.ScrnCntrl.cfg ..\English\w0.ScrnCntrl.cfg
fsutil hardlink create w0.Text.cfg ..\English\w0.Text.cfg
fsutil hardlink create w0.v1.cfg ..\English\w0.v1.cfg
fsutil hardlink create w0.v2.cfg ..\English\w0.v2.cfg
fsutil hardlink create w0.v3.cfg ..\English\w0.v3.cfg
fsutil hardlink create w1.cfg ..\English\w1.cfg
fsutil hardlink create w1.Text.cfg ..\English\w1.Text.cfg
fsutil hardlink create w2.cfg ..\English\w2.cfg
fsutil hardlink create w2.Text.cfg ..\English\w2.Text.cfg
fsutil hardlink create w3.Text.cfg ..\English\w3.Text.cfg
fsutil hardlink create w4.cfg ..\English\w4.cfg
fsutil hardlink create w4.Text.cfg ..\English\w4.Text.cfg
fsutil hardlink create w5.cfg ..\English\w5.cfg
fsutil hardlink create WinMgr.cfg ..\English\WinMgr.cfg
fsutil hardlink create WKpi.cfg ..\English\WKpi.cfg
