fsutil hardlink create Actions.cfg ..\English\Actions.cfg
fsutil hardlink create Calib.cfg ..\English\Calib.cfg
fsutil hardlink create DPrior.cfg ..\English\DPrior.cfg
fsutil hardlink create Delay.cfg ..\English\Delay.cfg
fsutil hardlink create Delay2.cfg ..\English\Delay2.cfg
fsutil hardlink create Delay3.cfg ..\English\Delay3.cfg
fsutil hardlink create Delay4.cfg ..\English\Delay4.cfg
fsutil hardlink create Delayloc.cfg ..\English\Delayloc.cfg
fsutil hardlink create Down.cfg ..\English\Down.cfg
fsutil hardlink create Down2.cfg ..\English\Down2.cfg
fsutil hardlink create Down3.cfg ..\English\Down3.cfg
fsutil hardlink create Down4.cfg ..\English\Down4.cfg
fsutil hardlink create FlashCntrl.cfg ..\English\FlashCntrl.cfg
fsutil hardlink create GeomMaster.cfg ..\English\GeomMaster.cfg
fsutil hardlink create Goic.cfg ..\English\Goic.cfg
fsutil hardlink create Info.cfg ..\English\Info.cfg
fsutil hardlink create Kn.cfg ..\English\Kn.cfg
fsutil hardlink create Kp.cfg ..\English\Kp.cfg
fsutil hardlink create Kp2.cfg ..\English\Kp2.cfg
fsutil hardlink create Ks.cfg ..\English\Ks.cfg
fsutil hardlink create Ku.cfg ..\English\Ku.cfg
fsutil hardlink create Load.cfg ..\English\Load.cfg
fsutil hardlink create Location.cfg ..\English\Location.cfg
fsutil hardlink create MPrior.cfg ..\English\MPrior.cfg
fsutil hardlink create Macro.video.cfg ..\English\Macro.video.cfg
fsutil hardlink create ManAsn.cfg ..\English\ManAsn.cfg
fsutil hardlink create Material2.cfg ..\English\Material2.cfg
fsutil hardlink create Message.cfg ..\English\Message.cfg
fsutil hardlink create Ok.cfg ..\English\Ok.cfg
fsutil hardlink create Options.Video.cfg ..\English\Options.Video.cfg
fsutil hardlink create PS_Message.cfg ..\English\PS_Message.cfg
fsutil hardlink create PgMenu.cfg ..\English\PgMenu.cfg
fsutil hardlink create Prestart.cfg ..\English\Prestart.cfg
fsutil hardlink create Prior.cfg ..\English\Prior.cfg
fsutil hardlink create ProdCount.cfg ..\English\ProdCount.cfg
fsutil hardlink create README.now ..\English\README.now
fsutil hardlink create Ready.cfg ..\English\Ready.cfg
fsutil hardlink create Ready2.cfg ..\English\Ready2.cfg
fsutil hardlink create Ready3.cfg ..\English\Ready3.cfg
fsutil hardlink create Ready4.cfg ..\English\Ready4.cfg
fsutil hardlink create Standby.cfg ..\English\Standby.cfg
fsutil hardlink create Standby2.cfg ..\English\Standby2.cfg
fsutil hardlink create Standby3.cfg ..\English\Standby3.cfg
fsutil hardlink create Standby4.cfg ..\English\Standby4.cfg
fsutil hardlink create Status.cfg ..\English\Status.cfg
fsutil hardlink create Tasks.cfg ..\English\Tasks.cfg
fsutil hardlink create TestInstall.cfg ..\English\TestInstall.cfg
fsutil hardlink create w0.Icon.cfg ..\English\w0.Icon.cfg
fsutil hardlink create w0.Kill.cfg ..\English\w0.Kill.cfg
fsutil hardlink create w0.ScrnCntrl.cfg ..\English\w0.ScrnCntrl.cfg
fsutil hardlink create w0.Sl1.cfg ..\English\w0.Sl1.cfg
fsutil hardlink create w0.Sl2.cfg ..\English\w0.Sl2.cfg
fsutil hardlink create w0.v3.cfg ..\English\w0.v3.cfg
fsutil hardlink create wk.Clock.cfg ..\English\wk.Clock.cfg
fsutil hardlink create wk.Kill.cfg ..\English\wk.Kill.cfg
fsutil hardlink create wk.cfg ..\English\wk.cfg
fsutil hardlink create wk.mb.cfg ..\English\wk.mb.cfg
fsutil hardlink create wk.sch.cfg ..\English\wk.sch.cfg
fsutil hardlink create wk.v1.cfg ..\English\wk.v1.cfg
fsutil hardlink create wk.v2.cfg ..\English\wk.v2.cfg
fsutil hardlink create wk.v3.cfg ..\English\wk.v3.cfg
fsutil hardlink create FatgTest.cfg ..\English\FatgTest.cfg
fsutil hardlink create w0.Comm.cfg ..\English\w0.Comm.cfg
fsutil hardlink create Macro_newui.cfg ..\English\Macro_newui.cfg
