DELETE FROM RPCSPL 
WHERE RPC!='LOGON' AND RPC!='DELAY' AND RPC!='DOWN' AND RPC!='READY' AND RPC!='STANDBY' AND RPC!='ASSIGN' AND 
RPC!='ARRIVE' AND RPC!='LOAD' AND RPC!='FULL' AND RPC!='PRESTART' AND RPC!='EQ-REQ' AND RPC!='GPS-ARRIVE' AND 
RPC!='GPS-DEPART' AND RPC!='RFID-ARRIVE' AND RPC!='RFID-DEPART' AND RPC!='SFDATA' AND RPC!='EQ-REQ'
GO