SELECT TOP 1000 ID,EVTTIME,HOST,RPC,DATA 
FROM RPCSPL WHERE STATUS=1 AND 
(RPC='SFDATA' OR RPC='EQ-REQ' OR RPC='LOGON' OR RPC='DELAY' OR RPC='DOWN' OR RPC='READY' OR RPC='STANDBY' 
OR RPC='ASSIGN' OR RPC='ARRIVE' OR RPC='LOAD' OR RPC='FULL' OR RPC='PRESTART' OR RPC='EQ-REQ' OR RPC='GPS-ARRIVE' 
OR RPC='GPS-DEPART' OR RPC='RFID-ARRIVE' OR RPC='RFID-DEPART') ORDER BY ID
GO
