#ifndef LANGUAGE
#	define LANGUAGE English
#endif
CP(Demo/WinMgr.cfg,CFG/WinMgr.cfg)
CP(Demo/LANGUAGE/country.icon,CFG/country.icon)
CP(Demo/LANGUAGE/Goic.cfg,CFG/Goic.cfg)
CP(Demo/LANGUAGE/w0.cfg,CFG/w0.cfg)
CP(Demo/LANGUAGE/w0.mb.cfg,CFG/w0.mb.cfg)
CP(Demo/LANGUAGE/w0.Icon.cfg,CFG/w0.Icon.cfg)
CP(Demo/LANGUAGE/w0.sl1.cfg,CFG/w0.sl1.cfg)
CP(Demo/LANGUAGE/w0.sl2.cfg,CFG/w0.sl2.cfg)
CP(Demo/LANGUAGE/w1.cfg,CFG/w1.cfg)
CP(Demo/LANGUAGE/w1.mb.cfg,CFG/w1.mb.cfg)
CP(Demo/LANGUAGE/w2.cfg,CFG/w2.cfg)
CP(Demo/LANGUAGE/w2.Icon.cfg,CFG/w2.Icon.cfg)
CP(Demo/LANGUAGE/w2.Defects.cfg,CFG/w2.Defects.cfg)
CP(Demo/LANGUAGE/w2.Label.cfg,CFG/w2.Label.cfg)
CP(Demo/LANGUAGE/w2.OK.cfg,CFG/w2.OK.cfg)
CP(Demo/LANGUAGE/Kp.cfg,CFG/Kp.cfg)
CP(Demo/LANGUAGE/Options.cfg,CFG/Options.cfg)
CP(Demo/LANGUAGE/Actions.cfg,CFG/Actions.cfg)
CP(Demo/LANGUAGE/Status.cfg,CFG/Status.cfg)
CP(Demo/LANGUAGE/Language.cfg,CFG/Language.cfg)
CP(Demo/LANGUAGE/Delay.cfg,CFG/Delay.cfg)
CP(Demo/LANGUAGE/Down.cfg,CFG/Down.cfg)
CP(Demo/LANGUAGE/Standby.cfg,CFG/Standby.cfg)
CP(Demo/LANGUAGE/Displays.cfg,CFG/Displays.cfg)
CP(Demo/LANGUAGE/Touch.cfg,CFG/Touch.cfg)
